name: CommandPurchaseGUI
main: com.gmail.justbru00.computersmp.custom.enchants.gui.main.Main
version: 1.0-SNAPSHOT
description: A Plugin
author: Justin Brubaker
depend: [Vault]

commands:
 commandpurchasegui:
       description: I am too lazy for this description.     
 buycommand:
       description: I am too lazy for this description.
  