name: ComputerSMP
main: com.gmail.justbru00.computersmp.custom.enchants.gui.main.Main
version: 1.3
description: A Plugin
author: Justin Brubaker
depend: [Vault]

commands:
 commandpurchasegui:
       description: I am too lazy for this description.     
 buycommand:
       description: I am too lazy for this description.
 withdraw:
       description: I am too lazy for this description.
 disableplugin:
       description: LOL
 enableplugin:
       description: LOL